### PR TITLE
Change the import of fact_plots.plotting module.

### PR DESCRIPTION
**Pull request by nbiederbeck**
Error was something of the lines 'could not make relative import' so I changed it locally and it worked for me.

### CODE REVIEW

**Comment by maxnoe** [comment]
No, it was correct before. However it requires that you use the installed module.

**Comment by maxnoe** [comment]
What exactly did you do and what was the exact error message?

**Comment by nbiederbeck** [comment]
1. running `pip install -e .` in the home folder of this repository.
2. `cd` into `fact_plots/scripts`
3. running `python plot_bias_resolution.py` gives the error code
```python
Traceback (most recent call last):
  File "plot_bias_resolution.py", line 6, in <module>
    from ..plotting import add_preliminary
SystemError: Parent module '' not loaded, cannot perform relative import
```

In iPython I can do
```python
from fact_plots.scripts import plot_bias_resolution
```
without an error.
But I thought running the `plot_bias_resolution.py` script from CLI should work too

**Comment by maxnoe** [comment]
This is expected behaviour.

The scripts ate installed into you path, you are not supposed to run them by going into the directory and doing python script.py.

just run `fact_plot_bias_reaolution` anywhere

**Pull request closed without merging**
